services:
  nginx-proxy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - skynet

  app1:
    image: nginx:latest
    container_name: app1
    restart: always
    volumes:
      - ./app1:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - skynet

  app2:
    image: nginx:latest
    container_name: app2
    restart: always
    volumes:
      - ./app2:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16